ARGIN ?= 1
ifeq ($(ARGIN), 1)
	# @echo "I am super!"
endif


python, py:
	@python main.py

test:
	@echo "I am super!"
ifeq ($(ARGIN), 1)
	@echo "I am super!"
endif

.PHONY: clean
clean: 
	@echo "Clean"